### ISSUE TITLE
Invalid Notebook

### ISSUE THREAD

**Issue by amiralisahraei** [Ebimsv/Machine_Learning_Course#1]
Hello.
I'm receiving an "Invalid Notebook" error when trying to open these files :
12. KDTree_BallTree.ipynb   
14. Clustering.ipynb
16. PCA.ipynb
18. Random Forest.ipynb 
I would appreciate it if you could take a look at it.

**Comment by Ebimsv** [comment]
Hello
Sorry, I haven't updated this section yet, but I have given explanations in Medium (Day 16 of Machine learning series). Read this link and I will update this section as soon as possible.

link:
https://medium.com/@ebimsv/ml-series-day-16-improving-knn-efficiency-using-kd-trees-and-ball-trees-for-faster-algorithms-99ece01a408c

**Comment by amiralisahraei** [comment]
Thanks
